### PR TITLE
docs: add prd

### PR DESCRIPTION
**Pull request by Keith-CY**
This PR concludes PRD snippets from https://github.com/Magickbase/ckb-explorer-public-issues/issues/60

Preview: https://github.com/Magickbase/ckb-explorer-public-issues/blob/add-prd/PRD.md

### CODE REVIEW

**Comment by Keith-CY** [comment]
Any questions about the fields and their explanations could be added as a comment and I'll enrich them.

There're some details that should be confirmed from the code and need help from @ShiningRay 
1. Definition of `Occupied` on the address page: https://github.com/Magickbase/ckb-explorer-public-issues/pull/73/files#diff-f3f7b39d67748ec7d5da458a1bb1f98cf05f47d4e121c582f090e23280afd8f1R187
2. Algorithms of all charts: https://github.com/Magickbase/ckb-explorer-public-issues/pull/73/files#diff-f3f7b39d67748ec7d5da458a1bb1f98cf05f47d4e121c582f090e23280afd8f1R325

Please update them by proposing a **suggestion** during the review as https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/reviewing-changes-in-pull-requests/commenting-on-a-pull-request (mentioned in point 6)

**Review by ShiningRay — DISMISSED** [review]

**Comment by Keith-CY** [comment]
Chapter Nervos DAO is missing @Keith-CY

**Comment by Keith-CY** [comment]
> Any questions about the fields and their explanations could be added as a comment and I'll enrich them.
> 
> There're some details that should be confirmed from the code and need help from @ShiningRay
> 
> 1. Definition of `Occupied` on the address page: https://github.com/Magickbase/ckb-explorer-public-issues/pull/73/files#diff-f3f7b39d67748ec7d5da458a1bb1f98cf05f47d4e121c582f090e23280afd8f1R187
> 2. Algorithms of all charts: https://github.com/Magickbase/ckb-explorer-public-issues/pull/73/files#diff-f3f7b39d67748ec7d5da458a1bb1f98cf05f47d4e121c582f090e23280afd8f1R325
> 
> Please update them by proposing a **suggestion** during the review as https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/reviewing-changes-in-pull-requests/commenting-on-a-pull-request (mentioned in point 6)

Added by https://github.com/Magickbase/ckb-explorer-public-issues/pull/84

**Comment by Keith-CY** [comment]
I'll add PRD of Nervos DAO in another PR

**Pull request merged**
